steps:

  # Docker Build Product Listener service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'gcr.io/${PROJECT_ID}/learn_microservice/product-listener',
           'product_listener_srv']

  # Docker Push Product Listener service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'gcr.io/${PROJECT_ID}/learn_microservice/product-listener']