// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: product/product_q.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchProduct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page int64  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Q    string `protobuf:"bytes,2,opt,name=q,proto3" json:"q,omitempty"`
}

func (x *SearchProduct) Reset() {
	*x = SearchProduct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_product_product_q_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProduct) ProtoMessage() {}

func (x *SearchProduct) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_q_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProduct.ProtoReflect.Descriptor instead.
func (*SearchProduct) Descriptor() ([]byte, []int) {
	return file_product_product_q_proto_rawDescGZIP(), []int{0}
}

func (x *SearchProduct) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchProduct) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

type SearchProductResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Products []*ProductShowcase `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
}

func (x *SearchProductResult) Reset() {
	*x = SearchProductResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_product_product_q_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchProductResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductResult) ProtoMessage() {}

func (x *SearchProductResult) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_q_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductResult.ProtoReflect.Descriptor instead.
func (*SearchProductResult) Descriptor() ([]byte, []int) {
	return file_product_product_q_proto_rawDescGZIP(), []int{1}
}

func (x *SearchProductResult) GetProducts() []*ProductShowcase {
	if x != nil {
		return x.Products
	}
	return nil
}

type ProductShowcase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Stock int64  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
}

func (x *ProductShowcase) Reset() {
	*x = ProductShowcase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_product_product_q_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductShowcase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductShowcase) ProtoMessage() {}

func (x *ProductShowcase) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_q_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductShowcase.ProtoReflect.Descriptor instead.
func (*ProductShowcase) Descriptor() ([]byte, []int) {
	return file_product_product_q_proto_rawDescGZIP(), []int{2}
}

func (x *ProductShowcase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductShowcase) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

var File_product_product_q_proto protoreflect.FileDescriptor

var file_product_product_q_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x5f, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x73, 0x72, 0x76, 0x2e, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x71, 0x22, 0x31, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x0c, 0x0a,
	0x01, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x71, 0x22, 0x51, 0x0a, 0x13, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x3a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x5f, 0x71, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x68, 0x6f, 0x77,
	0x63, 0x61, 0x73, 0x65, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x22, 0x3b,
	0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x68, 0x6f, 0x77, 0x63, 0x61, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x32, 0x63, 0x0a, 0x13, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x4c, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x1c, 0x2e, 0x73,
	0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x71, 0x2e, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x1a, 0x22, 0x2e, 0x73, 0x72, 0x76,
	0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x71, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00,
	0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_product_product_q_proto_rawDescOnce sync.Once
	file_product_product_q_proto_rawDescData = file_product_product_q_proto_rawDesc
)

func file_product_product_q_proto_rawDescGZIP() []byte {
	file_product_product_q_proto_rawDescOnce.Do(func() {
		file_product_product_q_proto_rawDescData = protoimpl.X.CompressGZIP(file_product_product_q_proto_rawDescData)
	})
	return file_product_product_q_proto_rawDescData
}

var file_product_product_q_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_product_product_q_proto_goTypes = []interface{}{
	(*SearchProduct)(nil),       // 0: srv.product_q.SearchProduct
	(*SearchProductResult)(nil), // 1: srv.product_q.SearchProductResult
	(*ProductShowcase)(nil),     // 2: srv.product_q.ProductShowcase
}
var file_product_product_q_proto_depIdxs = []int32{
	2, // 0: srv.product_q.SearchProductResult.products:type_name -> srv.product_q.ProductShowcase
	0, // 1: srv.product_q.ProductQueryService.Search:input_type -> srv.product_q.SearchProduct
	1, // 2: srv.product_q.ProductQueryService.Search:output_type -> srv.product_q.SearchProductResult
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_product_product_q_proto_init() }
func file_product_product_q_proto_init() {
	if File_product_product_q_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_product_product_q_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchProduct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_product_product_q_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchProductResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_product_product_q_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductShowcase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_product_product_q_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_product_q_proto_goTypes,
		DependencyIndexes: file_product_product_q_proto_depIdxs,
		MessageInfos:      file_product_product_q_proto_msgTypes,
	}.Build()
	File_product_product_q_proto = out.File
	file_product_product_q_proto_rawDesc = nil
	file_product_product_q_proto_goTypes = nil
	file_product_product_q_proto_depIdxs = nil
}
