// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: product/product_q.proto

package product

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProductQueryServiceClient is the client API for ProductQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductQueryServiceClient interface {
	Search(ctx context.Context, in *SearchProduct, opts ...grpc.CallOption) (*SearchProductResult, error)
}

type productQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductQueryServiceClient(cc grpc.ClientConnInterface) ProductQueryServiceClient {
	return &productQueryServiceClient{cc}
}

func (c *productQueryServiceClient) Search(ctx context.Context, in *SearchProduct, opts ...grpc.CallOption) (*SearchProductResult, error) {
	out := new(SearchProductResult)
	err := c.cc.Invoke(ctx, "/srv.product_q.ProductQueryService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductQueryServiceServer is the server API for ProductQueryService service.
// All implementations must embed UnimplementedProductQueryServiceServer
// for forward compatibility
type ProductQueryServiceServer interface {
	Search(context.Context, *SearchProduct) (*SearchProductResult, error)
	mustEmbedUnimplementedProductQueryServiceServer()
}

// UnimplementedProductQueryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProductQueryServiceServer struct {
}

func (UnimplementedProductQueryServiceServer) Search(context.Context, *SearchProduct) (*SearchProductResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedProductQueryServiceServer) mustEmbedUnimplementedProductQueryServiceServer() {}

// UnsafeProductQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductQueryServiceServer will
// result in compilation errors.
type UnsafeProductQueryServiceServer interface {
	mustEmbedUnimplementedProductQueryServiceServer()
}

func RegisterProductQueryServiceServer(s grpc.ServiceRegistrar, srv ProductQueryServiceServer) {
	s.RegisterService(&ProductQueryService_ServiceDesc, srv)
}

func _ProductQueryService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchProduct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductQueryServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/srv.product_q.ProductQueryService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductQueryServiceServer).Search(ctx, req.(*SearchProduct))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductQueryService_ServiceDesc is the grpc.ServiceDesc for ProductQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "srv.product_q.ProductQueryService",
	HandlerType: (*ProductQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _ProductQueryService_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product/product_q.proto",
}
