apiVersion: v1
kind: ConfigMap
metadata:
  name: product-command-config
data:
  MYSQL_DATABASE: "app"
  MYSQL_USER: "db_user"
  MYSQL_ROOT_PASSWORD: "db_user_pass"
  MYSQL_PASSWORD: "db_user_pass"
  MYSQL_PORT: "3306"
  MYSQL_HOST: "mysql-product-command"

---
apiVersion: v1
kind: Service
metadata:
  name: product-command-service
spec:
  selector:
    app: product-command
  ports:
    - port: 443
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-command
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-command
  template:
    metadata:
      labels:
        app: product-command
    spec:
      containers:
        - name: product-command
          image: smallker/learn_microservice-product_command_service:0.0.1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: config
            - configMapRef:
                name: product-command-config
          env:
            - name: PORT
              value: "3000"
            - name: ENV
              value: "DEV"

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-product-command
spec:
  selector:
    app: mysql-product-command
  ports:
    - port: 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-product-command
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-product-command
  template:
    metadata:
      name: mysql-product-command
      labels:
        app: mysql-product-command
    spec:
      volumes:
        - name: mysql-volume
          emptyDir: {}
      containers:
        - name: mysql-product-command
          image: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-volume
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: product-command-config
