apiVersion: v1
kind: ConfigMap
metadata:
  name: product-query-config
data:
  MYSQL_DATABASE: "app"
  MYSQL_USER: "db_user"
  MYSQL_ROOT_PASSWORD: "db_user_pass"
  MYSQL_PASSWORD: "db_user_pass"
  MYSQL_PORT: "3306"
  MYSQL_HOST: "mysql-db"

---
apiVersion: v1
kind: Service
metadata:
  name: product-query-service
spec:
  selector:
    app: product-query
  ports:
    - port: 443
      targetPort: 3002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-query
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-query
  template:
    metadata:
      labels:
        app: product-query
    spec:
      containers:
        - name: query
          image: registry.dev.svc.cluster.local:62119/product_q:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: config
            - configMapRef:
                name: product-query-config
          env:
            - name: PORT
              value: "3002"
        - name: listener
          image: registry.dev.svc.cluster.local:62119/product_listener:0.0.2
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: config
            - configMapRef:
                name: product-query-config
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-db
spec:
  selector:
    app: mysql-db
  ports:
    - port: 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      name: mysql-db
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql-db
          image: mysql
          envFrom:
            - configMapRef:
                name: product-query-config