apiVersion: v1
kind: Service
metadata:
  name: message-broker-service
spec:
  selector:
    app: message-broker
  ports:
    - port: 5672
      targetPort: 5672

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-broker
  template:
    metadata:
      name: message-broker
      labels:
        app: message-broker
    spec:
      containers:
        - name: message-broker
          image: rabbitmq
          ports:
            - containerPort: 5672